// frontend/src/components/interview/InterviewListItem.vue
<template>
  <v-card class="mx-auto" max-width="344" variant="outlined">
    <v-card-item>
      <div>
        <div class="text-h6 mb-1">{{ this.interview.title }}</div>
        <v-divider class="mb-1"></v-divider>
        <div class="text-caption">
          <p>내용 : {{ this.interview.description }}</p>
          <p>
            모집 기간 : {{ this.interview.apply_start_time }} ~
            {{ this.interview.apply_end_time }}
          </p>
          <p>
            대상자 : {{ this.interview.start_standard_age }}~{{
              this.interview.end_standard_age
            }}세
            {{ this.gender }}
          </p>
          <p>지급 포인트 : {{ this.interview.point }}P</p>
        </div>
      </div>
    </v-card-item>

    <v-card-actions class="float-right">
      <v-btn variant="outlined"> 상세보기 </v-btn>
    </v-card-actions>
  </v-card>
</template>

<script>
export default {
  name: "InterviewListItem",
  props: ["interview"],
  components: {},
  data() {
    return {
      gender: "",
      open: false,
    };
  },
  created() {
    if (this.interview.gender == "W") this.gender = "여성";
    else if (this.interview.gender == "M") this.gender = "남성";
    else this.gender = "상관없음";
  },
};
</script>

<style scoped></style>

// frontend/src/components/InterviewListItem.jsx
import React from "react";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Typography from "@mui/material/Typography";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemIcon from "@mui/material/ListItemIcon";
import ListItemText from "@mui/material/ListItemText";
import Divider from "@mui/material/Divider";
import PersonRoundedIcon from "@mui/icons-material/PersonRounded";
import ContentPasteRoundedIcon from "@mui/icons-material/ContentPasteRounded";
import AccessTimeRoundedIcon from "@mui/icons-material/AccessTimeRounded";
import PaidRoundedIcon from "@mui/icons-material/PaidRounded";

export default function interviewListItem(props) {
  return (
    <div>
      <Card sx={{ minHeight: 300 }}>
        <CardContent>
          <Typography align="left" gutterBottom variant="h5" component="div">
            {props.interview.title}
          </Typography>

          <Divider />

          <List>
            <ListItem disablePadding>
              <ListItemIcon>
                <ContentPasteRoundedIcon />
              </ListItemIcon>
              <ListItemText primary={props.interview.description} />
            </ListItem>
            <ListItem disablePadding>
              <ListItemIcon>
                <PersonRoundedIcon />
              </ListItemIcon>
              <ListItemText>
                {props.interview.start_standard_age}~
                {props.interview.end_standard_age}세{" "}
                {props.interview.gender === "W" && "여성"}
                {props.interview.gender === "M" && "남성"}
                {props.interview.gender === "O" && "상관없음"}
              </ListItemText>
            </ListItem>
            <ListItem disablePadding>
              <ListItemIcon>
                <AccessTimeRoundedIcon />
              </ListItemIcon>
              <ListItemText>
                {props.interview.apply_start_time} ~
                {props.interview.apply_end_time}
              </ListItemText>
            </ListItem>
            <ListItem disablePadding>
              <ListItemIcon>
                <PaidRoundedIcon />
              </ListItemIcon>
              <ListItemText primary={props.interview.point} />
            </ListItem>
          </List>
        </CardContent>
      </Card>
    </div>
  );
}
