// frontend/src/components/interview/InterviewList.vue
<template>
  <v-row justify="center">
    <v-col cols="8">
      <v-row>
        <v-col
          v-for="interview in interviews"
          :key="interview.id"
          :interview="interview"
          cols="4"
        >
          <interview-list-item :interview="interview"> </interview-list-item>
        </v-col>
      </v-row>
    </v-col>
  </v-row>
</template>

<script>
import InterviewListItem from "@/components/interview/InterviewListItem.vue";
import getList from "@/components/interview/interview_list.json";
export default {
  name: "InterviewList",
  components: { InterviewListItem },
  data() {
    return {
      interviews: getList.interview_list,
    };
  },
};
</script>

<style scoped></style>

// frontend/src/components/InterviewList.jsx
import React from "react";
import getList from "../json/interview_list";
import Grid from "@mui/material/Grid";
import Container from "@mui/material/Container";
import InterviewListItem from "./InterviewListItem";
import "./InterviewList.css";

export default function InterviewList() {
  const newList = getList.interview_list.map((item, index) => {
    return item;
  });
  return (
    <div className="interviewList">
      <Container maxWidth="xl">
        <Grid container spacing={{ xs: 2, md: 3 }}>
          {newList.map((interview) => (
            <Grid item sm={12} md={6} lg={4} xl={3} key={interview.id}>
              <InterviewListItem interview={interview} />
            </Grid>
          ))}
        </Grid>
      </Container>
    </div>
  );
}
